// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:f545917d-dcfc-4a17-99ad-c4165fcbc052",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_L1YfoDb3z",
    "aws_user_pools_web_client_id": "5cmpg1ra6r7c6a3e2mpe94om0v",
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "ShawnTable",
            "region": "us-east-1"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "apie2d281e1",
            "endpoint": "https://uf95okuhoa.execute-api.us-east-1.amazonaws.com/Prod",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
