// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
  "aws_project_region": "us-east-1",
  "aws_cognito_identity_pool_id": "us-east-1:835e5b34-4bf4-4cca-8211-2ff032831ec8",
  "aws_cognito_region": "us-east-1",
  "aws_user_pools_id": "us-east-1_APfLACHhT",
  "aws_user_pools_web_client_id": "7to0bm5863j3clskcfnno8jl47"
};


export default awsmobile;
