// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:771e40e0-3033-4f19-9bca-e78902d7ac8d",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_zyPTAxQYt",
    "aws_user_pools_web_client_id": "64eeuhsmsvse167na08r2smaes",
    "aws_mobile_analytics_app_id": "d0813ab4551940538de947b86773f930",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
