// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:8a6080a9-2716-432d-b11f-42b808bf94c4",
    "aws_cognito_region": "us-east-1",
    "aws_mobile_analytics_app_id": "4f4ee2a1bb5649c3ad6ce36db172b5b1",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
